assetic:
    bundles: ['AppBundle', 'SymfonyIdAdminBundle', 'FOSUserBundle']
    node: '/usr/bin/nodejs' #change to your path
    filters:
        cssrewrite:
            apply_to: '\.css$'
#        uglifyjs2:
#            bin: /usr/local/bin/uglifyjs #change to your path
#            apply_to: '\.js$'
#        uglifycss:
#            bin: /usr/local/bin/uglifycss #change to your path
#            apply_to: '\.css$'

framework:
    translator: { fallbacks: ["%locale%"] }

knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true

knp_menu:
    twig:
        template: knp_menu.html.twig
    templating: false
    default_renderer: twig

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: 'Ihsan\AppBundle\Entity\User'

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: 'redis://localhost'
    session:
        prefix: 'SymfonyIdAdminSKeleton' #change this prefix
        client: default

symfonyid_admin:
    app_title: 'SYMFONYID ADMIN BUNDLE'
    app_short_title: 'SIAB'
    per_page: 10
    identifier: 'id'
    max_records: 1000
    date_time_format: 'd-m-Y'
    menu:
        name: 'symfonyid_menu'
        loader: 'symfonyid.admin.menu.default_menu_loader'
        path: '@AppBundle/Resources/config/menu.yml'
    upload_dir: 'uploads'
    driver: 'orm' #odm or both
    translation_domain: 'AppBundle'
    filters: ['name']
    number_format:
        decimal_precision: 0
        decimal_separator: ','
        thousand_separator: '.'
    user:
        form_class: 'symfonyid.admin.form.user_form'
        model_class: 'AppBundle\Entity\User'
        auto_enable: true
        show_fields: ['fullName', 'username', 'email', 'roles', 'enabled']
        grid_columns: ['fullName', 'username', 'email', 'roles', 'enabled']
        profile_fields: ['fullName', 'username', 'email', 'roles', 'enabled']
        filters: ['fullName', 'username']
        password_form: 'symfonyid.admin.form.change_password_form'
    themes:
        dashboard: 'SymfonyIdAdminBundle:Index:index.html.twig'
        profile: 'SymfonyIdAdminBundle:Index:profile.html.twig'
        change_password: 'SymfonyIdAdminBundle:Index:change_password.html.twig'
        form_theme: 'SymfonyIdAdminBundle:Form:fields.html.twig'
        new_view: 'SymfonyIdAdminBundle:Crud:new.html.twig'
        bulk_new_view: 'SymfonyIdAdminBundle:Crud:bulk-new.html.twig'
        edit_view: 'SymfonyIdAdminBundle:Crud:new.html.twig'
        show_view: 'SymfonyIdAdminBundle:Crud:show.html.twig'
        list_view: 'SymfonyIdAdminBundle:Crud:list.html.twig'
        pagination: 'SymfonyIdAdminBundle:Layout:pagination.html.twig'