imports:
    - { resource: elasticsearch.yml }
    - { resource: queue.yml }
    - { resource: bootstrap.yml }
    - { resource: admin.yml }
    - { resource: redis.yml }

assetic:
    bundles: ['AppBundle', 'SymfonyIdAdminBundle', 'FOSUserBundle']
    node: '/usr/bin/nodejs' #change to your path
    filters:
        less:
            node: /usr/local/bin/node #change to your path
            node_paths: [/usr/local/lib/node_modules] #change to your path
            apply_to: '\.less$'
        cssrewrite:
            apply_to: '\.css$'
        uglifyjs2:
            bin: /usr/local/bin/uglifyjs #change to your path
            apply_to: '\.js$'
        uglifycss:
            bin: /usr/local/bin/uglifycss #change to your path
            apply_to: '\.css$'

framework:
    translator: { fallbacks: ['%locale%'] }

knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true

doctrine_mongodb:
    connections:
        default:
            server: '%mongodb_server%'
            options: {}
    default_database: '%database_name%'
    document_managers:
        default:
            auto_mapping: true

knp_menu:
    twig:
        template: knp_menu.html.twig
    templating: false
    default_renderer: twig

fos_user:
    db_driver: '%user_driver%'
    firewall_name: main
    user_class: '%user_class%'