snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: '%redis_server%'
    session:
        prefix: '%redis_prefix%' #change this prefix
        client: default