snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: '%redis_server%'
    session:
        prefix: '%redis_prefix%'
        client: default
    doctrine:
        metadata_cache:
            client: default
            entity_manager: default
            namespace: "dmc:"
        query_cache:
            client: default
            entity_manager: default
            namespace: "dqc:"
        result_cache:
            client: default
            entity_manager: default
            namespace: "drc:"
        second_level_cache:
            client: default
            entity_manager: default
            namespace: 'dslc:'

doctrine:
    orm:
        metadata_cache_driver:  redis
        query_cache_driver:     redis
        result_cache_driver:    redis
        second_level_cache:
            enabled:            true