services:
    app.exception_listener:
        class: Ihsan\AppBundle\EventListener\ExceptionListener
        arguments:
            - '@kernel'
            - '@logger'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }